# Generated by Django 5.0.6 on 2026-07-28 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisticElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('material', models.CharField(blank=True, max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='elements/covers/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('genre', models.CharField(help_text='e.g. Bridal Couture, Resort Wear, Avant-Garde', max_length=120)),
                ('season_year', models.CharField(blank=True, help_text='e.g. Spring/Summer 2026', max_length=60)),
                ('short_description', models.CharField(help_text='One-line summary shown on the collection grid.', max_length=300)),
                ('story', models.TextField(help_text='Longer narrative shown on the collection detail page.')),
                ('fabric_and_technique', models.CharField(blank=True, max_length=250)),
                ('cover_image', models.ImageField(upload_to='collections/covers/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls the 01, 02, 03... numbering on the site.')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CraftHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='craft/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Craft Highlight (Home page)',
                'verbose_name_plural': 'Craft Highlights (Home page)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tagline', models.CharField(blank=True, help_text="Short line shown under the name on the home page, e.g. 'Couturier of quiet excess'.", max_length=200)),
                ('home_intro', models.TextField(help_text='A short paragraph shown on the Home page.')),
                ('about_bio', models.TextField(help_text='Full biography shown on the About page.')),
                ('philosophy', models.TextField(blank=True, help_text='Design philosophy / statement, shown on the About page.')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='designer/')),
                ('about_image', models.ImageField(blank=True, help_text='Secondary image for the About page (studio, atelier, etc.).', null=True, upload_to='designer/')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('instagram_url', models.URLField(blank=True)),
                ('pinterest_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Designer Profile',
                'verbose_name_plural': 'Designer Profile',
            },
        ),
        migrations.CreateModel(
            name='ArtisticElementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='elements/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_photoshoot', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('artistic_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.artisticelement')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='artisticelement',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artistic_elements', to='core.collection'),
        ),
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collections/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_photoshoot', models.BooleanField(default=False, help_text='Tick if this is a photoshoot / behind-the-scenes image rather than a plain look shot.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.collection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('collection_of_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='core.collection')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
